// source: mappings.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

goog.provide('proto.AdditionalCriteria');
goog.provide('proto.AdditionalCriteria.BooleanValue');
goog.provide('proto.AdditionalCriteria.CategoricalQanda');
goog.provide('proto.AdditionalCriteria.CategoricalQanda.Criterion');
goog.provide('proto.AdditionalCriteria.NumericRange');
goog.provide('proto.AdditionalCriteria.ValueCriteriaCase');

goog.require('jspb.BinaryReader');
goog.require('jspb.BinaryWriter');
goog.require('jspb.Message');

/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.AdditionalCriteria = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, proto.AdditionalCriteria.oneofGroups_);
};
goog.inherits(proto.AdditionalCriteria, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.AdditionalCriteria.displayName = 'proto.AdditionalCriteria';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.AdditionalCriteria.CategoricalQanda = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.AdditionalCriteria.CategoricalQanda.repeatedFields_, null);
};
goog.inherits(proto.AdditionalCriteria.CategoricalQanda, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.AdditionalCriteria.CategoricalQanda.displayName = 'proto.AdditionalCriteria.CategoricalQanda';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.AdditionalCriteria.CategoricalQanda.Criterion = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.AdditionalCriteria.CategoricalQanda.Criterion, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.AdditionalCriteria.CategoricalQanda.Criterion.displayName = 'proto.AdditionalCriteria.CategoricalQanda.Criterion';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.AdditionalCriteria.NumericRange = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.AdditionalCriteria.NumericRange, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.AdditionalCriteria.NumericRange.displayName = 'proto.AdditionalCriteria.NumericRange';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.AdditionalCriteria.BooleanValue = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.AdditionalCriteria.BooleanValue, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.AdditionalCriteria.BooleanValue.displayName = 'proto.AdditionalCriteria.BooleanValue';
}

/**
 * Oneof group definitions for this message. Each group defines the field
 * numbers belonging to that group. When of these fields' value is set, all
 * other fields in the group are cleared. During deserialization, if multiple
 * fields are encountered for a group, only the last value seen will be kept.
 * @private {!Array<!Array<number>>}
 * @const
 */
proto.AdditionalCriteria.oneofGroups_ = [[2,3,4]];

/**
 * @enum {number}
 */
proto.AdditionalCriteria.ValueCriteriaCase = {
  VALUE_CRITERIA_NOT_SET: 0,
  CATEGORICAL: 2,
  NUMERIC: 3,
  BOOLEAN: 4
};

/**
 * @return {proto.AdditionalCriteria.ValueCriteriaCase}
 */
proto.AdditionalCriteria.prototype.getValueCriteriaCase = function() {
  return /** @type {proto.AdditionalCriteria.ValueCriteriaCase} */(jspb.Message.computeOneofCase(this, proto.AdditionalCriteria.oneofGroups_[0]));
};



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.AdditionalCriteria.prototype.toObject = function(opt_includeInstance) {
  return proto.AdditionalCriteria.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.AdditionalCriteria} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.AdditionalCriteria.toObject = function(includeInstance, msg) {
  var f, obj = {
    questionCode: jspb.Message.getFieldWithDefault(msg, 1, ""),
    categorical: (f = msg.getCategorical()) && proto.AdditionalCriteria.CategoricalQanda.toObject(includeInstance, f),
    numeric: (f = msg.getNumeric()) && proto.AdditionalCriteria.NumericRange.toObject(includeInstance, f),
    pb_boolean: (f = msg.getBoolean()) && proto.AdditionalCriteria.BooleanValue.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.AdditionalCriteria}
 */
proto.AdditionalCriteria.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.AdditionalCriteria;
  return proto.AdditionalCriteria.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.AdditionalCriteria} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.AdditionalCriteria}
 */
proto.AdditionalCriteria.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setQuestionCode(value);
      break;
    case 2:
      var value = new proto.AdditionalCriteria.CategoricalQanda;
      reader.readMessage(value,proto.AdditionalCriteria.CategoricalQanda.deserializeBinaryFromReader);
      msg.setCategorical(value);
      break;
    case 3:
      var value = new proto.AdditionalCriteria.NumericRange;
      reader.readMessage(value,proto.AdditionalCriteria.NumericRange.deserializeBinaryFromReader);
      msg.setNumeric(value);
      break;
    case 4:
      var value = new proto.AdditionalCriteria.BooleanValue;
      reader.readMessage(value,proto.AdditionalCriteria.BooleanValue.deserializeBinaryFromReader);
      msg.setBoolean(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.AdditionalCriteria.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.AdditionalCriteria.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.AdditionalCriteria} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.AdditionalCriteria.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getQuestionCode();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getCategorical();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      proto.AdditionalCriteria.CategoricalQanda.serializeBinaryToWriter
    );
  }
  f = message.getNumeric();
  if (f != null) {
    writer.writeMessage(
      3,
      f,
      proto.AdditionalCriteria.NumericRange.serializeBinaryToWriter
    );
  }
  f = message.getBoolean();
  if (f != null) {
    writer.writeMessage(
      4,
      f,
      proto.AdditionalCriteria.BooleanValue.serializeBinaryToWriter
    );
  }
};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.AdditionalCriteria.CategoricalQanda.repeatedFields_ = [1];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.AdditionalCriteria.CategoricalQanda.prototype.toObject = function(opt_includeInstance) {
  return proto.AdditionalCriteria.CategoricalQanda.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.AdditionalCriteria.CategoricalQanda} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.AdditionalCriteria.CategoricalQanda.toObject = function(includeInstance, msg) {
  var f, obj = {
    criterionList: jspb.Message.toObjectList(msg.getCriterionList(),
    proto.AdditionalCriteria.CategoricalQanda.Criterion.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.AdditionalCriteria.CategoricalQanda}
 */
proto.AdditionalCriteria.CategoricalQanda.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.AdditionalCriteria.CategoricalQanda;
  return proto.AdditionalCriteria.CategoricalQanda.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.AdditionalCriteria.CategoricalQanda} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.AdditionalCriteria.CategoricalQanda}
 */
proto.AdditionalCriteria.CategoricalQanda.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.AdditionalCriteria.CategoricalQanda.Criterion;
      reader.readMessage(value,proto.AdditionalCriteria.CategoricalQanda.Criterion.deserializeBinaryFromReader);
      msg.addCriterion(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.AdditionalCriteria.CategoricalQanda.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.AdditionalCriteria.CategoricalQanda.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.AdditionalCriteria.CategoricalQanda} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.AdditionalCriteria.CategoricalQanda.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getCriterionList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      1,
      f,
      proto.AdditionalCriteria.CategoricalQanda.Criterion.serializeBinaryToWriter
    );
  }
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.AdditionalCriteria.CategoricalQanda.Criterion.prototype.toObject = function(opt_includeInstance) {
  return proto.AdditionalCriteria.CategoricalQanda.Criterion.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.AdditionalCriteria.CategoricalQanda.Criterion} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.AdditionalCriteria.CategoricalQanda.Criterion.toObject = function(includeInstance, msg) {
  var f, obj = {
    key: jspb.Message.getFieldWithDefault(msg, 1, ""),
    value: jspb.Message.getFieldWithDefault(msg, 2, ""),
    unitOfMeasure: jspb.Message.getFieldWithDefault(msg, 3, ""),
    exclusive: jspb.Message.getBooleanFieldWithDefault(msg, 4, false)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.AdditionalCriteria.CategoricalQanda.Criterion}
 */
proto.AdditionalCriteria.CategoricalQanda.Criterion.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.AdditionalCriteria.CategoricalQanda.Criterion;
  return proto.AdditionalCriteria.CategoricalQanda.Criterion.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.AdditionalCriteria.CategoricalQanda.Criterion} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.AdditionalCriteria.CategoricalQanda.Criterion}
 */
proto.AdditionalCriteria.CategoricalQanda.Criterion.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setKey(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setValue(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setUnitOfMeasure(value);
      break;
    case 4:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setExclusive(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.AdditionalCriteria.CategoricalQanda.Criterion.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.AdditionalCriteria.CategoricalQanda.Criterion.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.AdditionalCriteria.CategoricalQanda.Criterion} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.AdditionalCriteria.CategoricalQanda.Criterion.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getKey();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getValue();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getUnitOfMeasure();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
  f = message.getExclusive();
  if (f) {
    writer.writeBool(
      4,
      f
    );
  }
};


/**
 * optional string key = 1;
 * @return {string}
 */
proto.AdditionalCriteria.CategoricalQanda.Criterion.prototype.getKey = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.AdditionalCriteria.CategoricalQanda.Criterion} returns this
 */
proto.AdditionalCriteria.CategoricalQanda.Criterion.prototype.setKey = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional string value = 2;
 * @return {string}
 */
proto.AdditionalCriteria.CategoricalQanda.Criterion.prototype.getValue = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.AdditionalCriteria.CategoricalQanda.Criterion} returns this
 */
proto.AdditionalCriteria.CategoricalQanda.Criterion.prototype.setValue = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional string unit_of_measure = 3;
 * @return {string}
 */
proto.AdditionalCriteria.CategoricalQanda.Criterion.prototype.getUnitOfMeasure = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/**
 * @param {string} value
 * @return {!proto.AdditionalCriteria.CategoricalQanda.Criterion} returns this
 */
proto.AdditionalCriteria.CategoricalQanda.Criterion.prototype.setUnitOfMeasure = function(value) {
  return jspb.Message.setProto3StringField(this, 3, value);
};


/**
 * optional bool exclusive = 4;
 * @return {boolean}
 */
proto.AdditionalCriteria.CategoricalQanda.Criterion.prototype.getExclusive = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 4, false));
};


/**
 * @param {boolean} value
 * @return {!proto.AdditionalCriteria.CategoricalQanda.Criterion} returns this
 */
proto.AdditionalCriteria.CategoricalQanda.Criterion.prototype.setExclusive = function(value) {
  return jspb.Message.setProto3BooleanField(this, 4, value);
};


/**
 * repeated Criterion criterion = 1;
 * @return {!Array<!proto.AdditionalCriteria.CategoricalQanda.Criterion>}
 */
proto.AdditionalCriteria.CategoricalQanda.prototype.getCriterionList = function() {
  return /** @type{!Array<!proto.AdditionalCriteria.CategoricalQanda.Criterion>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.AdditionalCriteria.CategoricalQanda.Criterion, 1));
};


/**
 * @param {!Array<!proto.AdditionalCriteria.CategoricalQanda.Criterion>} value
 * @return {!proto.AdditionalCriteria.CategoricalQanda} returns this
*/
proto.AdditionalCriteria.CategoricalQanda.prototype.setCriterionList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 1, value);
};


/**
 * @param {!proto.AdditionalCriteria.CategoricalQanda.Criterion=} opt_value
 * @param {number=} opt_index
 * @return {!proto.AdditionalCriteria.CategoricalQanda.Criterion}
 */
proto.AdditionalCriteria.CategoricalQanda.prototype.addCriterion = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 1, opt_value, proto.AdditionalCriteria.CategoricalQanda.Criterion, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.AdditionalCriteria.CategoricalQanda} returns this
 */
proto.AdditionalCriteria.CategoricalQanda.prototype.clearCriterionList = function() {
  return this.setCriterionList([]);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.AdditionalCriteria.NumericRange.prototype.toObject = function(opt_includeInstance) {
  return proto.AdditionalCriteria.NumericRange.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.AdditionalCriteria.NumericRange} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.AdditionalCriteria.NumericRange.toObject = function(includeInstance, msg) {
  var f, obj = {
    min: jspb.Message.getFloatingPointFieldWithDefault(msg, 1, 0.0),
    minInclusive: jspb.Message.getBooleanFieldWithDefault(msg, 2, false),
    max: jspb.Message.getFloatingPointFieldWithDefault(msg, 3, 0.0),
    maxInclusive: jspb.Message.getBooleanFieldWithDefault(msg, 4, false),
    unitOfMeasure: jspb.Message.getFieldWithDefault(msg, 5, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.AdditionalCriteria.NumericRange}
 */
proto.AdditionalCriteria.NumericRange.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.AdditionalCriteria.NumericRange;
  return proto.AdditionalCriteria.NumericRange.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.AdditionalCriteria.NumericRange} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.AdditionalCriteria.NumericRange}
 */
proto.AdditionalCriteria.NumericRange.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readDouble());
      msg.setMin(value);
      break;
    case 2:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setMinInclusive(value);
      break;
    case 3:
      var value = /** @type {number} */ (reader.readDouble());
      msg.setMax(value);
      break;
    case 4:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setMaxInclusive(value);
      break;
    case 5:
      var value = /** @type {string} */ (reader.readString());
      msg.setUnitOfMeasure(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.AdditionalCriteria.NumericRange.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.AdditionalCriteria.NumericRange.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.AdditionalCriteria.NumericRange} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.AdditionalCriteria.NumericRange.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getMin();
  if (f !== 0.0) {
    writer.writeDouble(
      1,
      f
    );
  }
  f = message.getMinInclusive();
  if (f) {
    writer.writeBool(
      2,
      f
    );
  }
  f = message.getMax();
  if (f !== 0.0) {
    writer.writeDouble(
      3,
      f
    );
  }
  f = message.getMaxInclusive();
  if (f) {
    writer.writeBool(
      4,
      f
    );
  }
  f = message.getUnitOfMeasure();
  if (f.length > 0) {
    writer.writeString(
      5,
      f
    );
  }
};


/**
 * optional double min = 1;
 * @return {number}
 */
proto.AdditionalCriteria.NumericRange.prototype.getMin = function() {
  return /** @type {number} */ (jspb.Message.getFloatingPointFieldWithDefault(this, 1, 0.0));
};


/**
 * @param {number} value
 * @return {!proto.AdditionalCriteria.NumericRange} returns this
 */
proto.AdditionalCriteria.NumericRange.prototype.setMin = function(value) {
  return jspb.Message.setProto3FloatField(this, 1, value);
};


/**
 * optional bool min_inclusive = 2;
 * @return {boolean}
 */
proto.AdditionalCriteria.NumericRange.prototype.getMinInclusive = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 2, false));
};


/**
 * @param {boolean} value
 * @return {!proto.AdditionalCriteria.NumericRange} returns this
 */
proto.AdditionalCriteria.NumericRange.prototype.setMinInclusive = function(value) {
  return jspb.Message.setProto3BooleanField(this, 2, value);
};


/**
 * optional double max = 3;
 * @return {number}
 */
proto.AdditionalCriteria.NumericRange.prototype.getMax = function() {
  return /** @type {number} */ (jspb.Message.getFloatingPointFieldWithDefault(this, 3, 0.0));
};


/**
 * @param {number} value
 * @return {!proto.AdditionalCriteria.NumericRange} returns this
 */
proto.AdditionalCriteria.NumericRange.prototype.setMax = function(value) {
  return jspb.Message.setProto3FloatField(this, 3, value);
};


/**
 * optional bool max_inclusive = 4;
 * @return {boolean}
 */
proto.AdditionalCriteria.NumericRange.prototype.getMaxInclusive = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 4, false));
};


/**
 * @param {boolean} value
 * @return {!proto.AdditionalCriteria.NumericRange} returns this
 */
proto.AdditionalCriteria.NumericRange.prototype.setMaxInclusive = function(value) {
  return jspb.Message.setProto3BooleanField(this, 4, value);
};


/**
 * optional string unit_of_measure = 5;
 * @return {string}
 */
proto.AdditionalCriteria.NumericRange.prototype.getUnitOfMeasure = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 5, ""));
};


/**
 * @param {string} value
 * @return {!proto.AdditionalCriteria.NumericRange} returns this
 */
proto.AdditionalCriteria.NumericRange.prototype.setUnitOfMeasure = function(value) {
  return jspb.Message.setProto3StringField(this, 5, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.AdditionalCriteria.BooleanValue.prototype.toObject = function(opt_includeInstance) {
  return proto.AdditionalCriteria.BooleanValue.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.AdditionalCriteria.BooleanValue} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.AdditionalCriteria.BooleanValue.toObject = function(includeInstance, msg) {
  var f, obj = {
    value: jspb.Message.getBooleanFieldWithDefault(msg, 1, false)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.AdditionalCriteria.BooleanValue}
 */
proto.AdditionalCriteria.BooleanValue.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.AdditionalCriteria.BooleanValue;
  return proto.AdditionalCriteria.BooleanValue.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.AdditionalCriteria.BooleanValue} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.AdditionalCriteria.BooleanValue}
 */
proto.AdditionalCriteria.BooleanValue.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setValue(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.AdditionalCriteria.BooleanValue.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.AdditionalCriteria.BooleanValue.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.AdditionalCriteria.BooleanValue} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.AdditionalCriteria.BooleanValue.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getValue();
  if (f) {
    writer.writeBool(
      1,
      f
    );
  }
};


/**
 * optional bool value = 1;
 * @return {boolean}
 */
proto.AdditionalCriteria.BooleanValue.prototype.getValue = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 1, false));
};


/**
 * @param {boolean} value
 * @return {!proto.AdditionalCriteria.BooleanValue} returns this
 */
proto.AdditionalCriteria.BooleanValue.prototype.setValue = function(value) {
  return jspb.Message.setProto3BooleanField(this, 1, value);
};


/**
 * optional string question_code = 1;
 * @return {string}
 */
proto.AdditionalCriteria.prototype.getQuestionCode = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.AdditionalCriteria} returns this
 */
proto.AdditionalCriteria.prototype.setQuestionCode = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional CategoricalQanda categorical = 2;
 * @return {?proto.AdditionalCriteria.CategoricalQanda}
 */
proto.AdditionalCriteria.prototype.getCategorical = function() {
  return /** @type{?proto.AdditionalCriteria.CategoricalQanda} */ (
    jspb.Message.getWrapperField(this, proto.AdditionalCriteria.CategoricalQanda, 2));
};


/**
 * @param {?proto.AdditionalCriteria.CategoricalQanda|undefined} value
 * @return {!proto.AdditionalCriteria} returns this
*/
proto.AdditionalCriteria.prototype.setCategorical = function(value) {
  return jspb.Message.setOneofWrapperField(this, 2, proto.AdditionalCriteria.oneofGroups_[0], value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.AdditionalCriteria} returns this
 */
proto.AdditionalCriteria.prototype.clearCategorical = function() {
  return this.setCategorical(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.AdditionalCriteria.prototype.hasCategorical = function() {
  return jspb.Message.getField(this, 2) != null;
};


/**
 * optional NumericRange numeric = 3;
 * @return {?proto.AdditionalCriteria.NumericRange}
 */
proto.AdditionalCriteria.prototype.getNumeric = function() {
  return /** @type{?proto.AdditionalCriteria.NumericRange} */ (
    jspb.Message.getWrapperField(this, proto.AdditionalCriteria.NumericRange, 3));
};


/**
 * @param {?proto.AdditionalCriteria.NumericRange|undefined} value
 * @return {!proto.AdditionalCriteria} returns this
*/
proto.AdditionalCriteria.prototype.setNumeric = function(value) {
  return jspb.Message.setOneofWrapperField(this, 3, proto.AdditionalCriteria.oneofGroups_[0], value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.AdditionalCriteria} returns this
 */
proto.AdditionalCriteria.prototype.clearNumeric = function() {
  return this.setNumeric(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.AdditionalCriteria.prototype.hasNumeric = function() {
  return jspb.Message.getField(this, 3) != null;
};


/**
 * optional BooleanValue boolean = 4;
 * @return {?proto.AdditionalCriteria.BooleanValue}
 */
proto.AdditionalCriteria.prototype.getBoolean = function() {
  return /** @type{?proto.AdditionalCriteria.BooleanValue} */ (
    jspb.Message.getWrapperField(this, proto.AdditionalCriteria.BooleanValue, 4));
};


/**
 * @param {?proto.AdditionalCriteria.BooleanValue|undefined} value
 * @return {!proto.AdditionalCriteria} returns this
*/
proto.AdditionalCriteria.prototype.setBoolean = function(value) {
  return jspb.Message.setOneofWrapperField(this, 4, proto.AdditionalCriteria.oneofGroups_[0], value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.AdditionalCriteria} returns this
 */
proto.AdditionalCriteria.prototype.clearBoolean = function() {
  return this.setBoolean(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.AdditionalCriteria.prototype.hasBoolean = function() {
  return jspb.Message.getField(this, 4) != null;
};


