// source: mappings.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

var jspb = require('google-protobuf');
var goog = jspb;
var global = (function() { return this || window || global || self || Function('return this')(); }).call(null);

goog.exportSymbol('proto.AdditionalCriteria', null, global);
goog.exportSymbol('proto.AdditionalCriteria.BooleanValue', null, global);
goog.exportSymbol('proto.AdditionalCriteria.CategoricalQanda', null, global);
goog.exportSymbol('proto.AdditionalCriteria.CategoricalQanda.Criterion', null, global);
goog.exportSymbol('proto.AdditionalCriteria.NumericRange', null, global);
goog.exportSymbol('proto.AdditionalCriteria.ValueCriteriaCase', null, global);
goog.exportSymbol('proto.FieldTestingSuiteObservationType', null, global);
goog.exportSymbol('proto.Mapping', null, global);
goog.exportSymbol('proto.MappingCollection', null, global);
goog.exportSymbol('proto.MappingCollection.BusinessUnit', null, global);
goog.exportSymbol('proto.QandAObservationType', null, global);
goog.exportSymbol('proto.QandAObservationType.Answer', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.Mapping = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.Mapping.repeatedFields_, null);
};
goog.inherits(proto.Mapping, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.Mapping.displayName = 'proto.Mapping';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.FieldTestingSuiteObservationType = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.FieldTestingSuiteObservationType, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.FieldTestingSuiteObservationType.displayName = 'proto.FieldTestingSuiteObservationType';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.QandAObservationType = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.QandAObservationType.repeatedFields_, null);
};
goog.inherits(proto.QandAObservationType, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.QandAObservationType.displayName = 'proto.QandAObservationType';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.QandAObservationType.Answer = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.QandAObservationType.Answer, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.QandAObservationType.Answer.displayName = 'proto.QandAObservationType.Answer';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.AdditionalCriteria = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, proto.AdditionalCriteria.oneofGroups_);
};
goog.inherits(proto.AdditionalCriteria, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.AdditionalCriteria.displayName = 'proto.AdditionalCriteria';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.AdditionalCriteria.CategoricalQanda = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.AdditionalCriteria.CategoricalQanda.repeatedFields_, null);
};
goog.inherits(proto.AdditionalCriteria.CategoricalQanda, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.AdditionalCriteria.CategoricalQanda.displayName = 'proto.AdditionalCriteria.CategoricalQanda';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.AdditionalCriteria.CategoricalQanda.Criterion = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.AdditionalCriteria.CategoricalQanda.Criterion, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.AdditionalCriteria.CategoricalQanda.Criterion.displayName = 'proto.AdditionalCriteria.CategoricalQanda.Criterion';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.AdditionalCriteria.NumericRange = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.AdditionalCriteria.NumericRange, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.AdditionalCriteria.NumericRange.displayName = 'proto.AdditionalCriteria.NumericRange';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.AdditionalCriteria.BooleanValue = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.AdditionalCriteria.BooleanValue, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.AdditionalCriteria.BooleanValue.displayName = 'proto.AdditionalCriteria.BooleanValue';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.MappingCollection = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.MappingCollection.repeatedFields_, null);
};
goog.inherits(proto.MappingCollection, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.MappingCollection.displayName = 'proto.MappingCollection';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.MappingCollection.BusinessUnit = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.MappingCollection.BusinessUnit, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.MappingCollection.BusinessUnit.displayName = 'proto.MappingCollection.BusinessUnit';
}

/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.Mapping.repeatedFields_ = [4];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.Mapping.prototype.toObject = function(opt_includeInstance) {
  return proto.Mapping.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.Mapping} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.Mapping.toObject = function(includeInstance, msg) {
  var f, obj = {
    name: jspb.Message.getFieldWithDefault(msg, 1, ""),
    fieldTestingSuiteObservationType: (f = msg.getFieldTestingSuiteObservationType()) && proto.FieldTestingSuiteObservationType.toObject(includeInstance, f),
    qandaObservationType: (f = msg.getQandaObservationType()) && proto.QandAObservationType.toObject(includeInstance, f),
    additionalCriteriaList: jspb.Message.toObjectList(msg.getAdditionalCriteriaList(),
    proto.AdditionalCriteria.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.Mapping}
 */
proto.Mapping.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.Mapping;
  return proto.Mapping.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.Mapping} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.Mapping}
 */
proto.Mapping.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setName(value);
      break;
    case 2:
      var value = new proto.FieldTestingSuiteObservationType;
      reader.readMessage(value,proto.FieldTestingSuiteObservationType.deserializeBinaryFromReader);
      msg.setFieldTestingSuiteObservationType(value);
      break;
    case 3:
      var value = new proto.QandAObservationType;
      reader.readMessage(value,proto.QandAObservationType.deserializeBinaryFromReader);
      msg.setQandaObservationType(value);
      break;
    case 4:
      var value = new proto.AdditionalCriteria;
      reader.readMessage(value,proto.AdditionalCriteria.deserializeBinaryFromReader);
      msg.addAdditionalCriteria(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.Mapping.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.Mapping.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.Mapping} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.Mapping.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getName();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getFieldTestingSuiteObservationType();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      proto.FieldTestingSuiteObservationType.serializeBinaryToWriter
    );
  }
  f = message.getQandaObservationType();
  if (f != null) {
    writer.writeMessage(
      3,
      f,
      proto.QandAObservationType.serializeBinaryToWriter
    );
  }
  f = message.getAdditionalCriteriaList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      4,
      f,
      proto.AdditionalCriteria.serializeBinaryToWriter
    );
  }
};


/**
 * optional string name = 1;
 * @return {string}
 */
proto.Mapping.prototype.getName = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.Mapping} returns this
 */
proto.Mapping.prototype.setName = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional FieldTestingSuiteObservationType field_testing_suite_observation_type = 2;
 * @return {?proto.FieldTestingSuiteObservationType}
 */
proto.Mapping.prototype.getFieldTestingSuiteObservationType = function() {
  return /** @type{?proto.FieldTestingSuiteObservationType} */ (
    jspb.Message.getWrapperField(this, proto.FieldTestingSuiteObservationType, 2));
};


/**
 * @param {?proto.FieldTestingSuiteObservationType|undefined} value
 * @return {!proto.Mapping} returns this
*/
proto.Mapping.prototype.setFieldTestingSuiteObservationType = function(value) {
  return jspb.Message.setWrapperField(this, 2, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.Mapping} returns this
 */
proto.Mapping.prototype.clearFieldTestingSuiteObservationType = function() {
  return this.setFieldTestingSuiteObservationType(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.Mapping.prototype.hasFieldTestingSuiteObservationType = function() {
  return jspb.Message.getField(this, 2) != null;
};


/**
 * optional QandAObservationType qanda_observation_type = 3;
 * @return {?proto.QandAObservationType}
 */
proto.Mapping.prototype.getQandaObservationType = function() {
  return /** @type{?proto.QandAObservationType} */ (
    jspb.Message.getWrapperField(this, proto.QandAObservationType, 3));
};


/**
 * @param {?proto.QandAObservationType|undefined} value
 * @return {!proto.Mapping} returns this
*/
proto.Mapping.prototype.setQandaObservationType = function(value) {
  return jspb.Message.setWrapperField(this, 3, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.Mapping} returns this
 */
proto.Mapping.prototype.clearQandaObservationType = function() {
  return this.setQandaObservationType(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.Mapping.prototype.hasQandaObservationType = function() {
  return jspb.Message.getField(this, 3) != null;
};


/**
 * repeated AdditionalCriteria additional_criteria = 4;
 * @return {!Array<!proto.AdditionalCriteria>}
 */
proto.Mapping.prototype.getAdditionalCriteriaList = function() {
  return /** @type{!Array<!proto.AdditionalCriteria>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.AdditionalCriteria, 4));
};


/**
 * @param {!Array<!proto.AdditionalCriteria>} value
 * @return {!proto.Mapping} returns this
*/
proto.Mapping.prototype.setAdditionalCriteriaList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 4, value);
};


/**
 * @param {!proto.AdditionalCriteria=} opt_value
 * @param {number=} opt_index
 * @return {!proto.AdditionalCriteria}
 */
proto.Mapping.prototype.addAdditionalCriteria = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 4, opt_value, proto.AdditionalCriteria, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.Mapping} returns this
 */
proto.Mapping.prototype.clearAdditionalCriteriaList = function() {
  return this.setAdditionalCriteriaList([]);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.FieldTestingSuiteObservationType.prototype.toObject = function(opt_includeInstance) {
  return proto.FieldTestingSuiteObservationType.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.FieldTestingSuiteObservationType} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.FieldTestingSuiteObservationType.toObject = function(includeInstance, msg) {
  var f, obj = {
    observationReference: jspb.Message.getFieldWithDefault(msg, 1, ""),
    cropObservationDetailId: jspb.Message.getFieldWithDefault(msg, 2, ""),
    midasGrowthStage: jspb.Message.getFieldWithDefault(msg, 3, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.FieldTestingSuiteObservationType}
 */
proto.FieldTestingSuiteObservationType.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.FieldTestingSuiteObservationType;
  return proto.FieldTestingSuiteObservationType.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.FieldTestingSuiteObservationType} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.FieldTestingSuiteObservationType}
 */
proto.FieldTestingSuiteObservationType.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setObservationReference(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setCropObservationDetailId(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setMidasGrowthStage(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.FieldTestingSuiteObservationType.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.FieldTestingSuiteObservationType.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.FieldTestingSuiteObservationType} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.FieldTestingSuiteObservationType.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getObservationReference();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getCropObservationDetailId();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getMidasGrowthStage();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
};


/**
 * optional string observation_reference = 1;
 * @return {string}
 */
proto.FieldTestingSuiteObservationType.prototype.getObservationReference = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.FieldTestingSuiteObservationType} returns this
 */
proto.FieldTestingSuiteObservationType.prototype.setObservationReference = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional string crop_observation_detail_id = 2;
 * @return {string}
 */
proto.FieldTestingSuiteObservationType.prototype.getCropObservationDetailId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.FieldTestingSuiteObservationType} returns this
 */
proto.FieldTestingSuiteObservationType.prototype.setCropObservationDetailId = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional string midas_growth_stage = 3;
 * @return {string}
 */
proto.FieldTestingSuiteObservationType.prototype.getMidasGrowthStage = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/**
 * @param {string} value
 * @return {!proto.FieldTestingSuiteObservationType} returns this
 */
proto.FieldTestingSuiteObservationType.prototype.setMidasGrowthStage = function(value) {
  return jspb.Message.setProto3StringField(this, 3, value);
};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.QandAObservationType.repeatedFields_ = [5];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.QandAObservationType.prototype.toObject = function(opt_includeInstance) {
  return proto.QandAObservationType.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.QandAObservationType} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.QandAObservationType.toObject = function(includeInstance, msg) {
  var f, obj = {
    entityType: jspb.Message.getFieldWithDefault(msg, 1, ""),
    questionClass: jspb.Message.getFieldWithDefault(msg, 2, ""),
    primaryQuestionCode: jspb.Message.getFieldWithDefault(msg, 3, ""),
    questionGroupInstance: jspb.Message.getFieldWithDefault(msg, 4, ""),
    uniqueAnswersList: jspb.Message.toObjectList(msg.getUniqueAnswersList(),
    proto.QandAObservationType.Answer.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.QandAObservationType}
 */
proto.QandAObservationType.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.QandAObservationType;
  return proto.QandAObservationType.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.QandAObservationType} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.QandAObservationType}
 */
proto.QandAObservationType.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setEntityType(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setQuestionClass(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setPrimaryQuestionCode(value);
      break;
    case 4:
      var value = /** @type {string} */ (reader.readString());
      msg.setQuestionGroupInstance(value);
      break;
    case 5:
      var value = new proto.QandAObservationType.Answer;
      reader.readMessage(value,proto.QandAObservationType.Answer.deserializeBinaryFromReader);
      msg.addUniqueAnswers(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.QandAObservationType.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.QandAObservationType.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.QandAObservationType} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.QandAObservationType.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getEntityType();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getQuestionClass();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getPrimaryQuestionCode();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
  f = message.getQuestionGroupInstance();
  if (f.length > 0) {
    writer.writeString(
      4,
      f
    );
  }
  f = message.getUniqueAnswersList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      5,
      f,
      proto.QandAObservationType.Answer.serializeBinaryToWriter
    );
  }
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.QandAObservationType.Answer.prototype.toObject = function(opt_includeInstance) {
  return proto.QandAObservationType.Answer.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.QandAObservationType.Answer} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.QandAObservationType.Answer.toObject = function(includeInstance, msg) {
  var f, obj = {
    questionCode: jspb.Message.getFieldWithDefault(msg, 1, ""),
    value: jspb.Message.getFieldWithDefault(msg, 2, ""),
    qandaKey: jspb.Message.getFieldWithDefault(msg, 3, ""),
    categoricalUnitOfMeasure: jspb.Message.getFieldWithDefault(msg, 4, ""),
    numericUnitOfMeasure: jspb.Message.getFieldWithDefault(msg, 5, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.QandAObservationType.Answer}
 */
proto.QandAObservationType.Answer.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.QandAObservationType.Answer;
  return proto.QandAObservationType.Answer.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.QandAObservationType.Answer} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.QandAObservationType.Answer}
 */
proto.QandAObservationType.Answer.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setQuestionCode(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setValue(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setQandaKey(value);
      break;
    case 4:
      var value = /** @type {string} */ (reader.readString());
      msg.setCategoricalUnitOfMeasure(value);
      break;
    case 5:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setNumericUnitOfMeasure(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.QandAObservationType.Answer.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.QandAObservationType.Answer.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.QandAObservationType.Answer} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.QandAObservationType.Answer.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getQuestionCode();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getValue();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getQandaKey();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
  f = message.getCategoricalUnitOfMeasure();
  if (f.length > 0) {
    writer.writeString(
      4,
      f
    );
  }
  f = message.getNumericUnitOfMeasure();
  if (f !== 0) {
    writer.writeInt64(
      5,
      f
    );
  }
};


/**
 * optional string question_code = 1;
 * @return {string}
 */
proto.QandAObservationType.Answer.prototype.getQuestionCode = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.QandAObservationType.Answer} returns this
 */
proto.QandAObservationType.Answer.prototype.setQuestionCode = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional string value = 2;
 * @return {string}
 */
proto.QandAObservationType.Answer.prototype.getValue = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.QandAObservationType.Answer} returns this
 */
proto.QandAObservationType.Answer.prototype.setValue = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional string qanda_key = 3;
 * @return {string}
 */
proto.QandAObservationType.Answer.prototype.getQandaKey = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/**
 * @param {string} value
 * @return {!proto.QandAObservationType.Answer} returns this
 */
proto.QandAObservationType.Answer.prototype.setQandaKey = function(value) {
  return jspb.Message.setProto3StringField(this, 3, value);
};


/**
 * optional string categorical_unit_of_measure = 4;
 * @return {string}
 */
proto.QandAObservationType.Answer.prototype.getCategoricalUnitOfMeasure = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 4, ""));
};


/**
 * @param {string} value
 * @return {!proto.QandAObservationType.Answer} returns this
 */
proto.QandAObservationType.Answer.prototype.setCategoricalUnitOfMeasure = function(value) {
  return jspb.Message.setProto3StringField(this, 4, value);
};


/**
 * optional int64 numeric_unit_of_measure = 5;
 * @return {number}
 */
proto.QandAObservationType.Answer.prototype.getNumericUnitOfMeasure = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 5, 0));
};


/**
 * @param {number} value
 * @return {!proto.QandAObservationType.Answer} returns this
 */
proto.QandAObservationType.Answer.prototype.setNumericUnitOfMeasure = function(value) {
  return jspb.Message.setProto3IntField(this, 5, value);
};


/**
 * optional string entity_type = 1;
 * @return {string}
 */
proto.QandAObservationType.prototype.getEntityType = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.QandAObservationType} returns this
 */
proto.QandAObservationType.prototype.setEntityType = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional string question_class = 2;
 * @return {string}
 */
proto.QandAObservationType.prototype.getQuestionClass = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.QandAObservationType} returns this
 */
proto.QandAObservationType.prototype.setQuestionClass = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional string primary_question_code = 3;
 * @return {string}
 */
proto.QandAObservationType.prototype.getPrimaryQuestionCode = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/**
 * @param {string} value
 * @return {!proto.QandAObservationType} returns this
 */
proto.QandAObservationType.prototype.setPrimaryQuestionCode = function(value) {
  return jspb.Message.setProto3StringField(this, 3, value);
};


/**
 * optional string question_group_instance = 4;
 * @return {string}
 */
proto.QandAObservationType.prototype.getQuestionGroupInstance = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 4, ""));
};


/**
 * @param {string} value
 * @return {!proto.QandAObservationType} returns this
 */
proto.QandAObservationType.prototype.setQuestionGroupInstance = function(value) {
  return jspb.Message.setProto3StringField(this, 4, value);
};


/**
 * repeated Answer unique_answers = 5;
 * @return {!Array<!proto.QandAObservationType.Answer>}
 */
proto.QandAObservationType.prototype.getUniqueAnswersList = function() {
  return /** @type{!Array<!proto.QandAObservationType.Answer>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.QandAObservationType.Answer, 5));
};


/**
 * @param {!Array<!proto.QandAObservationType.Answer>} value
 * @return {!proto.QandAObservationType} returns this
*/
proto.QandAObservationType.prototype.setUniqueAnswersList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 5, value);
};


/**
 * @param {!proto.QandAObservationType.Answer=} opt_value
 * @param {number=} opt_index
 * @return {!proto.QandAObservationType.Answer}
 */
proto.QandAObservationType.prototype.addUniqueAnswers = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 5, opt_value, proto.QandAObservationType.Answer, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.QandAObservationType} returns this
 */
proto.QandAObservationType.prototype.clearUniqueAnswersList = function() {
  return this.setUniqueAnswersList([]);
};



/**
 * Oneof group definitions for this message. Each group defines the field
 * numbers belonging to that group. When of these fields' value is set, all
 * other fields in the group are cleared. During deserialization, if multiple
 * fields are encountered for a group, only the last value seen will be kept.
 * @private {!Array<!Array<number>>}
 * @const
 */
proto.AdditionalCriteria.oneofGroups_ = [[2,3,4]];

/**
 * @enum {number}
 */
proto.AdditionalCriteria.ValueCriteriaCase = {
  VALUE_CRITERIA_NOT_SET: 0,
  CATEGORICAL: 2,
  NUMERIC: 3,
  BOOLEAN: 4
};

/**
 * @return {proto.AdditionalCriteria.ValueCriteriaCase}
 */
proto.AdditionalCriteria.prototype.getValueCriteriaCase = function() {
  return /** @type {proto.AdditionalCriteria.ValueCriteriaCase} */(jspb.Message.computeOneofCase(this, proto.AdditionalCriteria.oneofGroups_[0]));
};



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.AdditionalCriteria.prototype.toObject = function(opt_includeInstance) {
  return proto.AdditionalCriteria.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.AdditionalCriteria} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.AdditionalCriteria.toObject = function(includeInstance, msg) {
  var f, obj = {
    questionCode: jspb.Message.getFieldWithDefault(msg, 1, ""),
    categorical: (f = msg.getCategorical()) && proto.AdditionalCriteria.CategoricalQanda.toObject(includeInstance, f),
    numeric: (f = msg.getNumeric()) && proto.AdditionalCriteria.NumericRange.toObject(includeInstance, f),
    pb_boolean: (f = msg.getBoolean()) && proto.AdditionalCriteria.BooleanValue.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.AdditionalCriteria}
 */
proto.AdditionalCriteria.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.AdditionalCriteria;
  return proto.AdditionalCriteria.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.AdditionalCriteria} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.AdditionalCriteria}
 */
proto.AdditionalCriteria.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setQuestionCode(value);
      break;
    case 2:
      var value = new proto.AdditionalCriteria.CategoricalQanda;
      reader.readMessage(value,proto.AdditionalCriteria.CategoricalQanda.deserializeBinaryFromReader);
      msg.setCategorical(value);
      break;
    case 3:
      var value = new proto.AdditionalCriteria.NumericRange;
      reader.readMessage(value,proto.AdditionalCriteria.NumericRange.deserializeBinaryFromReader);
      msg.setNumeric(value);
      break;
    case 4:
      var value = new proto.AdditionalCriteria.BooleanValue;
      reader.readMessage(value,proto.AdditionalCriteria.BooleanValue.deserializeBinaryFromReader);
      msg.setBoolean(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.AdditionalCriteria.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.AdditionalCriteria.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.AdditionalCriteria} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.AdditionalCriteria.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getQuestionCode();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getCategorical();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      proto.AdditionalCriteria.CategoricalQanda.serializeBinaryToWriter
    );
  }
  f = message.getNumeric();
  if (f != null) {
    writer.writeMessage(
      3,
      f,
      proto.AdditionalCriteria.NumericRange.serializeBinaryToWriter
    );
  }
  f = message.getBoolean();
  if (f != null) {
    writer.writeMessage(
      4,
      f,
      proto.AdditionalCriteria.BooleanValue.serializeBinaryToWriter
    );
  }
};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.AdditionalCriteria.CategoricalQanda.repeatedFields_ = [1];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.AdditionalCriteria.CategoricalQanda.prototype.toObject = function(opt_includeInstance) {
  return proto.AdditionalCriteria.CategoricalQanda.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.AdditionalCriteria.CategoricalQanda} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.AdditionalCriteria.CategoricalQanda.toObject = function(includeInstance, msg) {
  var f, obj = {
    criterionList: jspb.Message.toObjectList(msg.getCriterionList(),
    proto.AdditionalCriteria.CategoricalQanda.Criterion.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.AdditionalCriteria.CategoricalQanda}
 */
proto.AdditionalCriteria.CategoricalQanda.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.AdditionalCriteria.CategoricalQanda;
  return proto.AdditionalCriteria.CategoricalQanda.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.AdditionalCriteria.CategoricalQanda} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.AdditionalCriteria.CategoricalQanda}
 */
proto.AdditionalCriteria.CategoricalQanda.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.AdditionalCriteria.CategoricalQanda.Criterion;
      reader.readMessage(value,proto.AdditionalCriteria.CategoricalQanda.Criterion.deserializeBinaryFromReader);
      msg.addCriterion(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.AdditionalCriteria.CategoricalQanda.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.AdditionalCriteria.CategoricalQanda.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.AdditionalCriteria.CategoricalQanda} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.AdditionalCriteria.CategoricalQanda.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getCriterionList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      1,
      f,
      proto.AdditionalCriteria.CategoricalQanda.Criterion.serializeBinaryToWriter
    );
  }
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.AdditionalCriteria.CategoricalQanda.Criterion.prototype.toObject = function(opt_includeInstance) {
  return proto.AdditionalCriteria.CategoricalQanda.Criterion.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.AdditionalCriteria.CategoricalQanda.Criterion} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.AdditionalCriteria.CategoricalQanda.Criterion.toObject = function(includeInstance, msg) {
  var f, obj = {
    key: jspb.Message.getFieldWithDefault(msg, 1, ""),
    value: jspb.Message.getFieldWithDefault(msg, 2, ""),
    unitOfMeasure: jspb.Message.getFieldWithDefault(msg, 3, ""),
    exclusive: jspb.Message.getBooleanFieldWithDefault(msg, 4, false)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.AdditionalCriteria.CategoricalQanda.Criterion}
 */
proto.AdditionalCriteria.CategoricalQanda.Criterion.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.AdditionalCriteria.CategoricalQanda.Criterion;
  return proto.AdditionalCriteria.CategoricalQanda.Criterion.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.AdditionalCriteria.CategoricalQanda.Criterion} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.AdditionalCriteria.CategoricalQanda.Criterion}
 */
proto.AdditionalCriteria.CategoricalQanda.Criterion.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setKey(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setValue(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setUnitOfMeasure(value);
      break;
    case 4:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setExclusive(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.AdditionalCriteria.CategoricalQanda.Criterion.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.AdditionalCriteria.CategoricalQanda.Criterion.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.AdditionalCriteria.CategoricalQanda.Criterion} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.AdditionalCriteria.CategoricalQanda.Criterion.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getKey();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getValue();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getUnitOfMeasure();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
  f = message.getExclusive();
  if (f) {
    writer.writeBool(
      4,
      f
    );
  }
};


/**
 * optional string key = 1;
 * @return {string}
 */
proto.AdditionalCriteria.CategoricalQanda.Criterion.prototype.getKey = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.AdditionalCriteria.CategoricalQanda.Criterion} returns this
 */
proto.AdditionalCriteria.CategoricalQanda.Criterion.prototype.setKey = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional string value = 2;
 * @return {string}
 */
proto.AdditionalCriteria.CategoricalQanda.Criterion.prototype.getValue = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.AdditionalCriteria.CategoricalQanda.Criterion} returns this
 */
proto.AdditionalCriteria.CategoricalQanda.Criterion.prototype.setValue = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional string unit_of_measure = 3;
 * @return {string}
 */
proto.AdditionalCriteria.CategoricalQanda.Criterion.prototype.getUnitOfMeasure = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/**
 * @param {string} value
 * @return {!proto.AdditionalCriteria.CategoricalQanda.Criterion} returns this
 */
proto.AdditionalCriteria.CategoricalQanda.Criterion.prototype.setUnitOfMeasure = function(value) {
  return jspb.Message.setProto3StringField(this, 3, value);
};


/**
 * optional bool exclusive = 4;
 * @return {boolean}
 */
proto.AdditionalCriteria.CategoricalQanda.Criterion.prototype.getExclusive = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 4, false));
};


/**
 * @param {boolean} value
 * @return {!proto.AdditionalCriteria.CategoricalQanda.Criterion} returns this
 */
proto.AdditionalCriteria.CategoricalQanda.Criterion.prototype.setExclusive = function(value) {
  return jspb.Message.setProto3BooleanField(this, 4, value);
};


/**
 * repeated Criterion criterion = 1;
 * @return {!Array<!proto.AdditionalCriteria.CategoricalQanda.Criterion>}
 */
proto.AdditionalCriteria.CategoricalQanda.prototype.getCriterionList = function() {
  return /** @type{!Array<!proto.AdditionalCriteria.CategoricalQanda.Criterion>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.AdditionalCriteria.CategoricalQanda.Criterion, 1));
};


/**
 * @param {!Array<!proto.AdditionalCriteria.CategoricalQanda.Criterion>} value
 * @return {!proto.AdditionalCriteria.CategoricalQanda} returns this
*/
proto.AdditionalCriteria.CategoricalQanda.prototype.setCriterionList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 1, value);
};


/**
 * @param {!proto.AdditionalCriteria.CategoricalQanda.Criterion=} opt_value
 * @param {number=} opt_index
 * @return {!proto.AdditionalCriteria.CategoricalQanda.Criterion}
 */
proto.AdditionalCriteria.CategoricalQanda.prototype.addCriterion = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 1, opt_value, proto.AdditionalCriteria.CategoricalQanda.Criterion, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.AdditionalCriteria.CategoricalQanda} returns this
 */
proto.AdditionalCriteria.CategoricalQanda.prototype.clearCriterionList = function() {
  return this.setCriterionList([]);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.AdditionalCriteria.NumericRange.prototype.toObject = function(opt_includeInstance) {
  return proto.AdditionalCriteria.NumericRange.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.AdditionalCriteria.NumericRange} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.AdditionalCriteria.NumericRange.toObject = function(includeInstance, msg) {
  var f, obj = {
    min: jspb.Message.getFloatingPointFieldWithDefault(msg, 1, 0.0),
    minInclusive: jspb.Message.getBooleanFieldWithDefault(msg, 2, false),
    max: jspb.Message.getFloatingPointFieldWithDefault(msg, 3, 0.0),
    maxInclusive: jspb.Message.getBooleanFieldWithDefault(msg, 4, false),
    unitOfMeasure: jspb.Message.getFieldWithDefault(msg, 5, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.AdditionalCriteria.NumericRange}
 */
proto.AdditionalCriteria.NumericRange.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.AdditionalCriteria.NumericRange;
  return proto.AdditionalCriteria.NumericRange.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.AdditionalCriteria.NumericRange} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.AdditionalCriteria.NumericRange}
 */
proto.AdditionalCriteria.NumericRange.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readDouble());
      msg.setMin(value);
      break;
    case 2:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setMinInclusive(value);
      break;
    case 3:
      var value = /** @type {number} */ (reader.readDouble());
      msg.setMax(value);
      break;
    case 4:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setMaxInclusive(value);
      break;
    case 5:
      var value = /** @type {string} */ (reader.readString());
      msg.setUnitOfMeasure(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.AdditionalCriteria.NumericRange.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.AdditionalCriteria.NumericRange.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.AdditionalCriteria.NumericRange} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.AdditionalCriteria.NumericRange.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getMin();
  if (f !== 0.0) {
    writer.writeDouble(
      1,
      f
    );
  }
  f = message.getMinInclusive();
  if (f) {
    writer.writeBool(
      2,
      f
    );
  }
  f = message.getMax();
  if (f !== 0.0) {
    writer.writeDouble(
      3,
      f
    );
  }
  f = message.getMaxInclusive();
  if (f) {
    writer.writeBool(
      4,
      f
    );
  }
  f = message.getUnitOfMeasure();
  if (f.length > 0) {
    writer.writeString(
      5,
      f
    );
  }
};


/**
 * optional double min = 1;
 * @return {number}
 */
proto.AdditionalCriteria.NumericRange.prototype.getMin = function() {
  return /** @type {number} */ (jspb.Message.getFloatingPointFieldWithDefault(this, 1, 0.0));
};


/**
 * @param {number} value
 * @return {!proto.AdditionalCriteria.NumericRange} returns this
 */
proto.AdditionalCriteria.NumericRange.prototype.setMin = function(value) {
  return jspb.Message.setProto3FloatField(this, 1, value);
};


/**
 * optional bool min_inclusive = 2;
 * @return {boolean}
 */
proto.AdditionalCriteria.NumericRange.prototype.getMinInclusive = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 2, false));
};


/**
 * @param {boolean} value
 * @return {!proto.AdditionalCriteria.NumericRange} returns this
 */
proto.AdditionalCriteria.NumericRange.prototype.setMinInclusive = function(value) {
  return jspb.Message.setProto3BooleanField(this, 2, value);
};


/**
 * optional double max = 3;
 * @return {number}
 */
proto.AdditionalCriteria.NumericRange.prototype.getMax = function() {
  return /** @type {number} */ (jspb.Message.getFloatingPointFieldWithDefault(this, 3, 0.0));
};


/**
 * @param {number} value
 * @return {!proto.AdditionalCriteria.NumericRange} returns this
 */
proto.AdditionalCriteria.NumericRange.prototype.setMax = function(value) {
  return jspb.Message.setProto3FloatField(this, 3, value);
};


/**
 * optional bool max_inclusive = 4;
 * @return {boolean}
 */
proto.AdditionalCriteria.NumericRange.prototype.getMaxInclusive = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 4, false));
};


/**
 * @param {boolean} value
 * @return {!proto.AdditionalCriteria.NumericRange} returns this
 */
proto.AdditionalCriteria.NumericRange.prototype.setMaxInclusive = function(value) {
  return jspb.Message.setProto3BooleanField(this, 4, value);
};


/**
 * optional string unit_of_measure = 5;
 * @return {string}
 */
proto.AdditionalCriteria.NumericRange.prototype.getUnitOfMeasure = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 5, ""));
};


/**
 * @param {string} value
 * @return {!proto.AdditionalCriteria.NumericRange} returns this
 */
proto.AdditionalCriteria.NumericRange.prototype.setUnitOfMeasure = function(value) {
  return jspb.Message.setProto3StringField(this, 5, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.AdditionalCriteria.BooleanValue.prototype.toObject = function(opt_includeInstance) {
  return proto.AdditionalCriteria.BooleanValue.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.AdditionalCriteria.BooleanValue} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.AdditionalCriteria.BooleanValue.toObject = function(includeInstance, msg) {
  var f, obj = {
    value: jspb.Message.getBooleanFieldWithDefault(msg, 1, false)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.AdditionalCriteria.BooleanValue}
 */
proto.AdditionalCriteria.BooleanValue.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.AdditionalCriteria.BooleanValue;
  return proto.AdditionalCriteria.BooleanValue.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.AdditionalCriteria.BooleanValue} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.AdditionalCriteria.BooleanValue}
 */
proto.AdditionalCriteria.BooleanValue.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setValue(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.AdditionalCriteria.BooleanValue.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.AdditionalCriteria.BooleanValue.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.AdditionalCriteria.BooleanValue} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.AdditionalCriteria.BooleanValue.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getValue();
  if (f) {
    writer.writeBool(
      1,
      f
    );
  }
};


/**
 * optional bool value = 1;
 * @return {boolean}
 */
proto.AdditionalCriteria.BooleanValue.prototype.getValue = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 1, false));
};


/**
 * @param {boolean} value
 * @return {!proto.AdditionalCriteria.BooleanValue} returns this
 */
proto.AdditionalCriteria.BooleanValue.prototype.setValue = function(value) {
  return jspb.Message.setProto3BooleanField(this, 1, value);
};


/**
 * optional string question_code = 1;
 * @return {string}
 */
proto.AdditionalCriteria.prototype.getQuestionCode = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.AdditionalCriteria} returns this
 */
proto.AdditionalCriteria.prototype.setQuestionCode = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional CategoricalQanda categorical = 2;
 * @return {?proto.AdditionalCriteria.CategoricalQanda}
 */
proto.AdditionalCriteria.prototype.getCategorical = function() {
  return /** @type{?proto.AdditionalCriteria.CategoricalQanda} */ (
    jspb.Message.getWrapperField(this, proto.AdditionalCriteria.CategoricalQanda, 2));
};


/**
 * @param {?proto.AdditionalCriteria.CategoricalQanda|undefined} value
 * @return {!proto.AdditionalCriteria} returns this
*/
proto.AdditionalCriteria.prototype.setCategorical = function(value) {
  return jspb.Message.setOneofWrapperField(this, 2, proto.AdditionalCriteria.oneofGroups_[0], value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.AdditionalCriteria} returns this
 */
proto.AdditionalCriteria.prototype.clearCategorical = function() {
  return this.setCategorical(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.AdditionalCriteria.prototype.hasCategorical = function() {
  return jspb.Message.getField(this, 2) != null;
};


/**
 * optional NumericRange numeric = 3;
 * @return {?proto.AdditionalCriteria.NumericRange}
 */
proto.AdditionalCriteria.prototype.getNumeric = function() {
  return /** @type{?proto.AdditionalCriteria.NumericRange} */ (
    jspb.Message.getWrapperField(this, proto.AdditionalCriteria.NumericRange, 3));
};


/**
 * @param {?proto.AdditionalCriteria.NumericRange|undefined} value
 * @return {!proto.AdditionalCriteria} returns this
*/
proto.AdditionalCriteria.prototype.setNumeric = function(value) {
  return jspb.Message.setOneofWrapperField(this, 3, proto.AdditionalCriteria.oneofGroups_[0], value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.AdditionalCriteria} returns this
 */
proto.AdditionalCriteria.prototype.clearNumeric = function() {
  return this.setNumeric(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.AdditionalCriteria.prototype.hasNumeric = function() {
  return jspb.Message.getField(this, 3) != null;
};


/**
 * optional BooleanValue boolean = 4;
 * @return {?proto.AdditionalCriteria.BooleanValue}
 */
proto.AdditionalCriteria.prototype.getBoolean = function() {
  return /** @type{?proto.AdditionalCriteria.BooleanValue} */ (
    jspb.Message.getWrapperField(this, proto.AdditionalCriteria.BooleanValue, 4));
};


/**
 * @param {?proto.AdditionalCriteria.BooleanValue|undefined} value
 * @return {!proto.AdditionalCriteria} returns this
*/
proto.AdditionalCriteria.prototype.setBoolean = function(value) {
  return jspb.Message.setOneofWrapperField(this, 4, proto.AdditionalCriteria.oneofGroups_[0], value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.AdditionalCriteria} returns this
 */
proto.AdditionalCriteria.prototype.clearBoolean = function() {
  return this.setBoolean(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.AdditionalCriteria.prototype.hasBoolean = function() {
  return jspb.Message.getField(this, 4) != null;
};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.MappingCollection.repeatedFields_ = [4,5];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.MappingCollection.prototype.toObject = function(opt_includeInstance) {
  return proto.MappingCollection.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.MappingCollection} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.MappingCollection.toObject = function(includeInstance, msg) {
  var f, obj = {
    name: jspb.Message.getFieldWithDefault(msg, 1, ""),
    displayName: jspb.Message.getFieldWithDefault(msg, 2, ""),
    application: jspb.Message.getFieldWithDefault(msg, 3, ""),
    businessUnitsList: jspb.Message.toObjectList(msg.getBusinessUnitsList(),
    proto.MappingCollection.BusinessUnit.toObject, includeInstance),
    mappingsList: jspb.Message.toObjectList(msg.getMappingsList(),
    proto.Mapping.toObject, includeInstance),
    annotationsMap: (f = msg.getAnnotationsMap()) ? f.toObject(includeInstance, undefined) : []
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.MappingCollection}
 */
proto.MappingCollection.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.MappingCollection;
  return proto.MappingCollection.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.MappingCollection} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.MappingCollection}
 */
proto.MappingCollection.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setName(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setDisplayName(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setApplication(value);
      break;
    case 4:
      var value = new proto.MappingCollection.BusinessUnit;
      reader.readMessage(value,proto.MappingCollection.BusinessUnit.deserializeBinaryFromReader);
      msg.addBusinessUnits(value);
      break;
    case 5:
      var value = new proto.Mapping;
      reader.readMessage(value,proto.Mapping.deserializeBinaryFromReader);
      msg.addMappings(value);
      break;
    case 6:
      var value = msg.getAnnotationsMap();
      reader.readMessage(value, function(message, reader) {
        jspb.Map.deserializeBinary(message, reader, jspb.BinaryReader.prototype.readString, jspb.BinaryReader.prototype.readString, null, "", "");
         });
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.MappingCollection.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.MappingCollection.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.MappingCollection} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.MappingCollection.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getName();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getDisplayName();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getApplication();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
  f = message.getBusinessUnitsList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      4,
      f,
      proto.MappingCollection.BusinessUnit.serializeBinaryToWriter
    );
  }
  f = message.getMappingsList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      5,
      f,
      proto.Mapping.serializeBinaryToWriter
    );
  }
  f = message.getAnnotationsMap(true);
  if (f && f.getLength() > 0) {
    f.serializeBinary(6, writer, jspb.BinaryWriter.prototype.writeString, jspb.BinaryWriter.prototype.writeString);
  }
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.MappingCollection.BusinessUnit.prototype.toObject = function(opt_includeInstance) {
  return proto.MappingCollection.BusinessUnit.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.MappingCollection.BusinessUnit} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.MappingCollection.BusinessUnit.toObject = function(includeInstance, msg) {
  var f, obj = {
    key: jspb.Message.getFieldWithDefault(msg, 1, ""),
    name: jspb.Message.getFieldWithDefault(msg, 2, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.MappingCollection.BusinessUnit}
 */
proto.MappingCollection.BusinessUnit.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.MappingCollection.BusinessUnit;
  return proto.MappingCollection.BusinessUnit.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.MappingCollection.BusinessUnit} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.MappingCollection.BusinessUnit}
 */
proto.MappingCollection.BusinessUnit.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setKey(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setName(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.MappingCollection.BusinessUnit.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.MappingCollection.BusinessUnit.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.MappingCollection.BusinessUnit} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.MappingCollection.BusinessUnit.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getKey();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getName();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
};


/**
 * optional string key = 1;
 * @return {string}
 */
proto.MappingCollection.BusinessUnit.prototype.getKey = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.MappingCollection.BusinessUnit} returns this
 */
proto.MappingCollection.BusinessUnit.prototype.setKey = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional string name = 2;
 * @return {string}
 */
proto.MappingCollection.BusinessUnit.prototype.getName = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.MappingCollection.BusinessUnit} returns this
 */
proto.MappingCollection.BusinessUnit.prototype.setName = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional string name = 1;
 * @return {string}
 */
proto.MappingCollection.prototype.getName = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.MappingCollection} returns this
 */
proto.MappingCollection.prototype.setName = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional string display_name = 2;
 * @return {string}
 */
proto.MappingCollection.prototype.getDisplayName = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.MappingCollection} returns this
 */
proto.MappingCollection.prototype.setDisplayName = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional string application = 3;
 * @return {string}
 */
proto.MappingCollection.prototype.getApplication = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/**
 * @param {string} value
 * @return {!proto.MappingCollection} returns this
 */
proto.MappingCollection.prototype.setApplication = function(value) {
  return jspb.Message.setProto3StringField(this, 3, value);
};


/**
 * repeated BusinessUnit business_units = 4;
 * @return {!Array<!proto.MappingCollection.BusinessUnit>}
 */
proto.MappingCollection.prototype.getBusinessUnitsList = function() {
  return /** @type{!Array<!proto.MappingCollection.BusinessUnit>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.MappingCollection.BusinessUnit, 4));
};


/**
 * @param {!Array<!proto.MappingCollection.BusinessUnit>} value
 * @return {!proto.MappingCollection} returns this
*/
proto.MappingCollection.prototype.setBusinessUnitsList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 4, value);
};


/**
 * @param {!proto.MappingCollection.BusinessUnit=} opt_value
 * @param {number=} opt_index
 * @return {!proto.MappingCollection.BusinessUnit}
 */
proto.MappingCollection.prototype.addBusinessUnits = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 4, opt_value, proto.MappingCollection.BusinessUnit, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.MappingCollection} returns this
 */
proto.MappingCollection.prototype.clearBusinessUnitsList = function() {
  return this.setBusinessUnitsList([]);
};


/**
 * repeated Mapping mappings = 5;
 * @return {!Array<!proto.Mapping>}
 */
proto.MappingCollection.prototype.getMappingsList = function() {
  return /** @type{!Array<!proto.Mapping>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.Mapping, 5));
};


/**
 * @param {!Array<!proto.Mapping>} value
 * @return {!proto.MappingCollection} returns this
*/
proto.MappingCollection.prototype.setMappingsList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 5, value);
};


/**
 * @param {!proto.Mapping=} opt_value
 * @param {number=} opt_index
 * @return {!proto.Mapping}
 */
proto.MappingCollection.prototype.addMappings = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 5, opt_value, proto.Mapping, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.MappingCollection} returns this
 */
proto.MappingCollection.prototype.clearMappingsList = function() {
  return this.setMappingsList([]);
};


/**
 * map<string, string> annotations = 6;
 * @param {boolean=} opt_noLazyCreate Do not create the map if
 * empty, instead returning `undefined`
 * @return {!jspb.Map<string,string>}
 */
proto.MappingCollection.prototype.getAnnotationsMap = function(opt_noLazyCreate) {
  return /** @type {!jspb.Map<string,string>} */ (
      jspb.Message.getMapField(this, 6, opt_noLazyCreate,
      null));
};


/**
 * Clears values from the map. The map will be non-null.
 * @return {!proto.MappingCollection} returns this
 */
proto.MappingCollection.prototype.clearAnnotationsMap = function() {
  this.getAnnotationsMap().clear();
  return this;};


goog.object.extend(exports, proto);
